/*************************
 * Foundations in Coding *       
 *************************
 *  IACT ** www.iact.ie  *
 *************************/

var noOfCircles = 100; //declare and initalise a variable to control the number of circles drawn
var xValues = []; //declare array to hold values for x-coordinates of circles
var yValues = []; //declare array for y-coordinate values
var count = 0; //will be used to step through the array and draw each circle in turn
function setup() {
    createCanvas(400, 400);
    frameRate(5);//slow it down
    noFill();        //don't use a fill colour
    stroke(50, 100, 75, 100); //pick a stroke colour for outlines
    background(255);

    //use a loop to step thorugh every element of each array and assign a value
    for (var i = 0; i < noOfCircles; i += 1) {
        xValues[i] = int(random(0, width)); //assign random values to the x-array..
        //... range of random values for x-coordinates varies between 0 and the width of the display
        yValues[i] = int(random(0, height));//assign random values to the y-array...
        //... range of random values for y-coordinates varies between 0 and the height of the display
        //Note that we need to convert from floating point numbers generated by random() to ints to store in the array
    }

}

function draw() {
    ellipse(xValues[count], yValues[count], 50, 50);
    if (count < noOfCircles) {
        count += 1;
    }


}